title: Simple Page

icon: 📝

status:
  draft: true
  unlisted:
    label: Hidden Page
    text: The page is not listed in the main menu
  listed:
    label: Menu Page
    text: The page is listed in the main menu

columns:
  - width: 1/1
    fields:
      content:
        extends: fields/body
