title: Project

status:
  listed: true
  draft: true

options:
  changeSlug: true
  delete: true
  changeTitle: true
  changeStatus: true
  preview: "https://modus.sdrvl.ch/project/{{ page.slug }}"

columns:
  - width: 1/1
    fields:
      content:
        extends: fields/body
        fields:
          headerImage:
            required: true
          showInNav: false
          body:
            fieldsets:
              - mdheading
              - body
              - mdimage
              - list
              - video
              - linksSection
      device:
        label: Dispositif
        type: select
        width: 1/2
        options:
          platform: La plateforme
          laboratory: Le laboratoire
          library: La Bibliothèque
          imaginary: La fabrique des imaginaires
          planting: La plantation

      date:
        required: false
        width: 1/2
        label: Date
        type: date
        default: false
        display: YYYY-MM

