title: Project

status:
  listed: true
  draft: true

options:
  changeSlug: true
  delete: true
  changeTitle: true
  changeStatus: true
  preview: "https://modus.sdrvl.ch/project/{{ page.slug }}"

columns:
  - width: 1/1
    fields:
      content:
        extends: fields/body
        fields:
          headerImage:
            required: true
          showInNav: false
          body:
            fieldsets:
              - mdheading
              - body
              - mdimage
              - list
              - video
              - linksSection
      device:
        label: Dispositif
        type: select
        width: 1/2
        options:
          platform: La plateforme
          laboratory: Le laboratoire
          library: La Bibliothèque
          imaginary: La fabrique des imaginaires
          planting: La plantation
  - width: 1/2
    fields:
      dateStart:
        required: true
        width: 1/1
        label: Date
        type: date
        display: YYYY-MM

      isProjectWithDuration:
        required: false
        type: toggle
        width: 1/2
        label: Ce projet a une date de fin, une durée?
        default: false

      dateEnd:
        required: false
        width: 1/1
        label: Date de fin
        type: date
        display: YYYY-MM
        when:
          isProjectWithDuration: true

