title: Profiles

preview: profiles

fields:

  title:
    label: titre
    type: text

  profiles:
    label: Profiles
    type: structure
    columns:
      image:
        width: 1/4
      name:
        width: 1/1
    fields:
      image:
        min: 0
        max: 1
        type: files
        layout: cards
        uploads:
          template: image
      name:
        label: Nom
        type: text
      description:
        label: Description
        type: text
