columns:
  - width: 1/2
    sections:
      pages:
        image: false
        type: pages
        create: default
        templates:
          - home
          - default
          - projects
          - outils-modus
