title: modus

options:
  preview: https://modus-ge.ch.ch/

columns:
  - width: 1/3
    fields:
      files:
        label:
          fr: Fichiers
        type: files
        layout: small
        uploads:
          template: pdf

  - width: 2/3
    sections:
      pages:
        image: false
        type: pages
        create: default
        templates:
          - home
          - default
          - default-admin
          - projects
          - outils-modus
