title: modus

options:
  preview: https://modus-ge.ch.ch/

columns:
  - width: 1/2
    sections:
      pages:
        image: false
        type: pages
        create: default
        templates:
          - home
          - default
          - default-admin
          - projects
          - outils-modus
